project_id = "hdebnqnuajtzudaozzti"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://hdebnqnuajtzudaozzti.lovableproject.com"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
security_update_password_require_reauthentication = false
enable_signup = true
enable_confirmations = false

[functions.generate-schedule]
verify_jwt = true